### ISSUE TITLE
End of profile creation dialog

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/testing-tickets#19]
On 19th July 2023, I typed "Doei" as a response to Sam's goodbye at the end of the profile creation dialog. The response from Sam was then a mix of the menu (as expected) and messages for doing a new activity. So I never got to respond to the menu, which was a bit confusing.

![image](https://github.com/PerfectFit-project/testing-tickets/assets/43779515/88defa96-3c26-4600-ab0a-4a0ad0845fe5)

![image](https://github.com/PerfectFit-project/testing-tickets/assets/43779515/fe0b07b7-fb3e-45b7-a637-f6274c0d389d)

**Comment by emeijerperfectfit** [comment]
Some other issues I encountered in the profile creation dialog (@nelealbers could you check these?):
1. I encountered some strange text in one of the example stories, of the woman who likes to go walking I think: please replace "zachte oefening" with "prettige oefening". Otherwise people might not feel related because of the itchy language used
2. could we use a scale ranging from 1 to 7 instead of -3 to 3? I think this is easier to understand for people unfamiliar with such scales (as most of our users will be) and also less sensitive to typos (e.g. if people forget to type the - ; or there is a space or something in between)
3. Could we add a bit more time between sending the story and asking the question? This made my husband feel hurried :p

**Comment by emeijerperfectfit** [comment]
Minor thing: 2 typos in this dialog. 
- When setting a date for the weekly reflection, the coach says diensdag instead of dinsdag
- Roolschaatsen should be rolschaatsen with single O
