### ISSUE TITLE
Video watching activities

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/testing-tickets#20]
1) I think it would be good to tell people before leaving to watch the video that the coach will be waiting for x minutes or so to give the user time to watch the video. Otherwise, if the user speeds through the video, he/she may wonder why the coach does not respond:

![WhatsApp Image 2023-07-19 at 10 21 49 AM](https://github.com/PerfectFit-project/testing-tickets/assets/43779515/37dff49c-4a49-48ac-b377-97974894363f)

2) Just sending the link without a transition when the user wants to re-watch the video seems a bit weird. I would expect something like "Here is the link again" first: 

![WhatsApp Image 2023-07-19 at 7 34 21 PM](https://github.com/PerfectFit-project/testing-tickets/assets/43779515/c878e1d2-b17b-4b1c-a33d-16ac83ac420b)

**Comment by nelealbers** [comment]
@emeijerperfectfit, could you take a look at these two points above?

**Comment by emeijerperfectfit** [comment]
Great suggestions. I'd suggest this Dutch text to solve this:
- point 1: Ik geef je nu even wat tijd om de video te bekijken. [insert as separate message after Je verlaat nu even de app. Je komt daarna weer terug in de app; I'd think that the specific time is not necessary here]
- point 2: Ik stuur je de link nog een keer. [insert as separate message before sending the link]

**Comment by nelealbers** [comment]
@emeijerperfectfit, okay, sounds good thanks!

**Comment by emeijerperfectfit** [comment]
I encountered a few other issues concerning videos:
- I got the same videos a couple of times, the one about tracking smoking and PA behaviors; as well as the future self video (long version) were sent a few times in different conversations. In the latter case this could be because the dialog was not yet finished (see below) but the tracking video was offered as an exercise and that seems odd
- At some point I got messages that I could watch a video but the link was missing. This seems like a bug, Sam did not move beyond this point. 
- I also got the 'watch video dialog' a couple of times without the options 1 and 2 for indicating whether it was clear (did not appear for long after the video had ended), so I couldn't continue. If I typed verder I got the same half-dialog without these options.

**Comment by emeijerperfectfit** [comment]
Nice to have: I think it might be useful if we would include the video's title in the video watching dialog, in case people would want to watch a video again (that would requiring some scrolling though). This is possible for the medication dialog through the menu but not for the other videos
Or perhaps create an option that they could request a list of the videos that they have watched so far, such that they can pick the one that they want to rewatch themselves

**Comment by emeijerperfectfit** [comment]
Comment by another tester: would it be possible to send the typ 1 voor duidelijk etc messages a bit sooner, in case you don't want to watch how you return to the app? perhaps video duration - 30 sec?

**Comment by emeijerperfectfit** [comment]
The sentence ‘Je komt daarna weer terug in de app’ seems confusing for some users, as they assume that this happens automatically. Could we replace this by ‘Je gaat daarna weer terug naar de app. Ik leg je uit hoe je dat kunt doen.’

**Comment by nelealbers** [comment]
I fixed the sentence "Je komt daarna weer terug in the app" here: https://github.com/PerfectFit-project/virtual-coach-rasa/pull/138
