### ISSUE TITLE
Users need to complete self-initiated HRS dialog to continue intervention

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/testing-tickets#25]
I noticed that upon starting the HRS dialog myself via "help" and not completing the dialog, I kept getting reminders to complete the dialog and without doing so, I could not proceed with the intervention. This might not be what we want, because people may already feel better after part of the HRS dialog and then they keep getting reminders to complete that dialog when they are no longer in a high-risk situation. 

If we want to change something about this, we also need to keep in mind that people with a relapse also need to set a new quit date.

@emeijerperfectfit, could you think about this?

**Comment by emeijerperfectfit** [comment]
That's indeed annoying. Would it work if we only send the regular reminder once, and then ask whether they want to complete the dialog or not,a nd stop sending reminders? --> "Ik vond het goed om je weer te spreken. Wil je deze dialoog nog afmaken? Typ '1' voor ja en typ '2' voor nee."
If they do not want to complete it then we can go back to the usual track. I'm not entirely sure though how this would affect the flow of the entire intervention

We would indeed need those who have relapsed to set a new quit date, so that would imply that they need a different reminder. Or perhaps it's easier that they get the reminders that we now have, and not the one that I suggested above. We may however need to send an additional message, "Laten we verder gaan waar we zijn gebleven, want je bent nog steeds goed op weg!" Would something like that?
