### ISSUE TITLE
Exercises

### ISSUE THREAD

**Issue by emeijerperfectfit** [PerfectFit-project/testing-tickets#28]
Some things around the exercises:
1. The persuasion questions are asked before the brief explanation of the exercise is given. I believe that for each exercise we had a short sentence of how it could help. I think that needs to be sent before the user is asked whether they have a reminder, why the exercise would help and so on. That's really difficult if you don't know what the exercise is about.
2. I did the exercise Terugdenken aan eerdere successen. Here Sam asks the user a couple of times to spend a couple of minutes on writing something down. I think that it needs to pause for at least one minute before sending the next message. Or was this a choice that we made for some reason?
3. Sam suggested the same video (keeping track of smoking and PA behavior) twice on 2 separate occasions, but it doesn't really make sense to watch this again if you've already done that

**Comment by emeijerperfectfit** [comment]
Another point: No questions are asked about helpfulness of the exercises; so do we get the information that we need to fill the first aid kit based on preferences?

**Comment by wbaccinelli** [comment]
1. I think that this flow was designed by @nelealbers? Maybe @emeijerperfectfit can discuss with her if and how to review this?
2. The exercises that are shown are just resources we load in. This means that there is not a specific flow for each exercise, but just a general one where we just change the text of the exercise according to the case. So it would be extremely difficult to add a pause in the middle of the exercise itself.
3. Could it be that the dialog was sent again because it was not completed the first time (i.e., no answer was given to the question: "Typ '1' voor 'duidelijk' en '2' voor 'nog een keer bekijken'")?
4. The question about helpfulness is asked at the beginning of the general activity dialog (if it's not the first time the dialog is executed). The user is asked to rate the helpfulness of the exercise that was executed the previous time. See the designed dialog's flow [here](https://leidenuniv1.sharepoint.com/:x:/r/sites/TeamAio/_layouts/15/Doc.aspx?sourcedoc=%7B07D07A3B-44F7-4B52-A431-891A484650D1%7D&file=FOR%20SPRINT%20SEPT%2027%20---%20C1.16%20General%20Activity%20Dialogue.xlsx&action=default&mobileredirect=true)

**Comment by emeijerperfectfit** [comment]
1. @nele could you have a look at this? I think you'd designed it a bit differently than what I saw now
2. ok that makes sense
3. that could be the case in one instance, but I think I also got the tracking video as an exercise that I had requested through the 'oefening' command. And once I got the short future self video through the oefening command, but before I had had the long version (which should come first)
4. I've never seen the general activity dialog so far! so something seems to go wrong there

**Comment by emeijerperfectfit** [comment]
4. I just got the general activuity dialog for the first time, but quite long after I did the previous exercise!

**Comment by wbaccinelli** [comment]
3. @emeijerperfectfit the tracking video is not part of the resources for the exercises, so it cannot be executed through the oefening command. Do you have a screen record or a time reference so that I can see what happened? 
The short video issue has been solved.

5. The 'oefening' command starts the general activity as specified in the [list of commands](https://leidenuniv1.sharepoint.com/:x:/r/sites/TeamAio/_layouts/15/Doc.aspx?sourcedoc=%7BEB76591D-CD0E-4F67-9C72-57DCBBC6E547%7D&file=FOR%20SPRINT%20FEB%208%20---%20List%20of%20commands.xlsx&action=default&mobileredirect=true).
What I mean is that if one executes an exercise through the GA dialog, he/she will be asked to rate it just the next time the GA dialog is executed, and not immediatly after the execution itself. There are activities that are mandatory at some time points (see  [here](https://leidenuniv1.sharepoint.com/:x:/r/sites/TeamAio/_layouts/15/Doc.aspx?sourcedoc=%7B1B69D6E4-49AA-438A-B3F2-602CEDBBFF9E%7D&file=2022.10.10_Perfect%20Fit%20app%20bible%20(Content%20overview%20and%20planning).xlsx&action=default&mobileredirect=true)), and the GA dialog is automatically sent by the coach in that case, as just happened to you.

**Comment by emeijerperfectfit** [comment]
3. no unfortunately not, let's see whether this comes up elsewhere, otherwise I'm probably mistaken. great that the short video is solved
4. clear! I think that the other dialogs were then unfinished such that the questions did not come. the exercise I did was referenced correctly

**Comment by nelealbers** [comment]
@emeijerperfectfit Regarding 1), this was also something that the people at the conference pointed out where we presented the demo in April. The statements about what the activities are useful for are used somewhere else, so we cannot use them before we ask those questions about having reminders, wanting to do an activity, etc. What we had discussed afterward with Milon and Kristell was that it would be good if the short titles for the activities were a bit more meaningful. This would also help with picking an activity, which the people at the conference found very difficult when the title is just super short and you have no idea what you are signing up for. And if these short titles are a bit longer, then the questions about having reminders etc. are also easier to answer. I am not sure if Milon or Kristell had already done something about this or not. But maybe based on your comment here they have not.

**Comment by emeijerperfectfit** [comment]
@nelealbers I believe I had changed the titles to be more meaningful, but now that I see them in the dialog it’s not sufficient for answering the questions, especially the open question about how this exercise may help to live a healthier live. I think for the 3 closed questions it’s ok, and it’s also enough to be able to pick an exercise.

What’s the reason that we can’t use the longer descriptions here as well? I think that if we ask the current open question we do need to provide more information first, otherwise I’m afraid it will only lead to frustration on the user’s side - rather than persuade them to do the exercise. 

If we can’t use the descriptions, would it make sense to develop slightly longer titles? Or is it possible to rephrase the open question to something like ‘Wat hoop je dat deze oefening je oplevert?’ That’s something that I think that people can answer more easily without having much information about the exercise.

**Comment by aversluis1** [comment]
@nelealbers @emeijerperfectfit , I had the same experience as Eline and was not able to answer the question. IF the last option that Eline suggested is used, we might also want to change the minimal character length and also accept shorter answers.

**Comment by emeijerperfectfit** [comment]
> @nelealbers @emeijerperfectfit , I had the same experience as Eline and was not able to answer the question. IF the last option that Eline suggested is used, we might also want to change the minimal character length and also accept shorter answers.

Good idea.

Btw: I’m on holiday after this week until August 15th and I hope not to check my mail, as otherwise my husband will make me pitch and tear down our tent.

**Comment by nelealbers** [comment]
@emeijerperfectfit @aversluis1 

First, regarding the titles for picking exercises, I still do not think that they are meaningful enough to help users pick exercises. For example, the title "Volhouden" - the user has no idea what he or she is going to do in that exercise. Or "Doe het anders" - the user has no idea what he or she is supposed to be doing differently. People who tried out our chatbot at the conference in April found this rather frustrating. I think the other short titles are better, but for these two activities at the very least it would be good to have something a bit more meaningful.

Second, regarding the open question, we can't change the formulation of the open question. The persuasion is based on what we tested in our study, so we should also use that. We could of course provide a bit more information before asking the question. If we do not change the titles for picking exercises to make them a bit more meaningful, we could add the slightly longer descriptions (not the instructions) when congratulating people for their activity choice. Right now we just say "Good choice!". But we could say something like "<activity_description> is a good choice!". Then it is easier to answer both the closed and the open question afterwards.

**Comment by aversluis1** [comment]
@nelealbers, the short titles are indeed not very informative with regard to what people will actually do in the exercise. I feel this is true for most of the titles and not just the two you mention. Would it be an idea / possible, to show the short titles. And once they have picked the exercise, to send a short message what the exericse is about. Then you can ask the persuasion questions. If this would be possible, I will make short descriptions for each exercise next week. 

Ahh, I just read your second point, so I think we have a similar idea. Shall I provide you with short descriptions for each activity? Then we could indeed congratulate them with their choice, and then say something like 'this activity is about .... '

**Comment by wbaccinelli** [comment]
@nelealbers @aversluis1 The activities come with a shot and a full title. For example, for the [Volhouden exercise](https://leidenuniv1.sharepoint.com/:x:/r/sites/TeamAio/_layouts/15/Doc.aspx?sourcedoc=%7B7A3D93CB-C0A7-4CA5-978C-E8AF9AE36C61%7D&file=FOR%20SPRINT%20FEB%208%20-%20C3.10%20%27Volhouden%27.xlsx&action=default&mobileredirect=true):

Short title: Volhouden
Full title: Volhouden op moeilijke momenten of wanneer anderen wel roken of niet bewegen.

Is this something we can already use maybe? 
@nelealbers this is already also in the DB in the `intervention_activity` table, under the `intervention_activity_description` field.

**Comment by aversluis1** [comment]
@wbaccinelli , these full titles are definitly useful! Where can I find this overview? Then  I can check whether they are fine or need some additions/changes.

**Comment by wbaccinelli** [comment]
@aversluis1 the are in the resources descriptions [here](https://leidenuniv1.sharepoint.com/sites/TeamAio/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x012000FF0493A502C07A42A0C04F2EC1F3A51D&id=%2Fsites%2FTeamAio%2FShared%20Documents%2FGeneral%2FContent%20folder%2FVirtual%20Coach%20Dialogs%20and%20Resources%2F3%20%2D%20C2%20%26%203%20Resources&viewid=c0b07892%2D4a36%2D4ab0%2D8d81%2Df9ac52e34585)

**Comment by nelealbers** [comment]
@wbaccinelli @aversluis1 Yes, I was thinking to use those intervention_activity_descriptions to say more about an activity after a user has chosen one. So if you agree, there is no more content needed for that and just a minor change in the implementation to say something like "This is what you picked: .... . Good choice!"

But I still think that the short meaningless titles are a challenge for picking an activity. I think it can be frustrating to be forced to pick an activity when you do not know what it entails, especially because people do not have the chance to change their choice afterwards.

**Comment by wbaccinelli** [comment]
@nelealbers but we can use them instead of the short titles, as in the ehbo. Or are they too long?

**Comment by nelealbers** [comment]
@wbaccinelli You mean in the activity selection? I think they are a bit too long for that. To make the titles for the activity selection more meaningful and usable, we would need something longer than the current titles and shorter than the current descriptions I think.

**Comment by wbaccinelli** [comment]
@nelealbers I don't know if the effort of adding a new description for all the resources with an in-between length is worth. I leave the decision to you and @aversluis1.

**Comment by nelealbers** [comment]
@wbaccinelli I think it depends on how long @aversluis1 thinks it would take.

In any case, I think we can create an issue to add the activity description to the sentence that congratulates people to their choice? So that people have more info when answering the closed and open questions afterward.

**Comment by aversluis1** [comment]
I think it is going to take me considerable time to come up with more meaningful short descriptions, so - for the sake of time - I will create an activity description for each activity that can be shown - as Nele suggested - after they have made their choice. I will do this at the end of the day.

**Comment by nelealbers** [comment]
> I think it is going to take me considerable time to come up with more meaningful short descriptions, so - for the sake of time - I will create an activity description for each activity that can be shown - as Nele suggested - after they have made their choice. I will do this at the end of the day.

@aversluis1 I do not think it is needed to create new content for this. We can just use what we already have in "activity_description" for each activity. We just need a dutch sentence that this can be incorporated in. Something like "Nice that you chose this activity: <activity_description>."

**Comment by aversluis1** [comment]
Ah I thought you wanted a slightly different description, but this only makes it easier. You could say: Je hebt gekozen voor de oefening: "full title" Goede keuze!

**Comment by nelealbers** [comment]
Okay, I have created an issue for this in the main repository.
