### ISSUE TITLE
Timing messages

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#43]
A user commented that it is somethings not clear when an open answer needs to be given or whether Sam will send a next message with answer  options. Also because Sam sometimes types slow. 
Example
Sam: ‘met wie was je toen je zin kreeg’
[zo’n tien seconden stilte]
Sam: ‘typ 1 als je met je partner was... etc.’

Because of the pause (which we of course implemented for a reason), it seemed to her like an open question. 
Would it be possible to put the question and the answer options in the same message, to avoid this confusion?

**Comment by wbaccinelli** [comment]
@aversluis1 In some cases it could be tricky, because if the user types an answer that is not valid (e.g., types 3 when 1 or 2 are expected), the VC will respond by sayin something like 'Can you please answer 1 or 2?' and than it will show the question again. So, it can be that he/she will receive a long long text again with the question in the end. This is an inbuilt Rasa behavior that we cannot change. 
In addition, The number of questions in the dialogs is quite large, and checking and changing all of them might require a large amount of time.
What do you think?

**Comment by aversluis1** [comment]
@wbaccinelli  I agree with you, might be too laborious to change.
