### ISSUE TITLE
Future self exercise

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#44]
29/7 I finally finished the long future self exercise, which kept coming back as I had either indicated too quickly that it was clear, or this question did not come (bug?). Immediately after finishing the long future self video, I got the short future self video (tester: Eline)

**Comment by wbaccinelli** [comment]
Yes, this is because the expected time between the long and the short version was passed, so the VC goes to the next expected dialog. In this testing phase, the short video is shown 3 days after the long one (8 days in the real intervention). This is the time the user is just expected to track his her behavior, as the tracking video has already been shown. Since the tracking period is over, the VC doesn't wait 8 more days to launch the new dialogs.
I agree that this case is a bit of confusing, but I don't know if it makes any sense to wait more days. An idea could be to not show the short version if they just got the long one. Or should we modify the flow in another direction?

**Comment by aversluis1** [comment]
The normal flow sounds okay, but in these specific cases can be confusing. Maybe good idea indeed to not show the short version if they just had the long one.
