### ISSUE TITLE
No scheduling dialog before the goal-setting dialog + start of goal-setting dialog

### ISSUE THREAD

**Issue by Milonvv** [PerfectFit-project/testing-tickets#72]
I was testing the intervention with the smartwatch connection. 

1) After I finished the future-self video dialog (during preparation phase), it immediately started the goal-setting dialog, without a scheduling dialog in between (see screenshot). However, I believe that the scheduling dialog first needs to be shown right?

2) This is a smaller issue, but the goal-setting dialog starts now with 'Hoi, wat leuk om je weer te spreken' (Hi, so nice to speak to you again) and then 'Hoe gaat het met je?' (How are you?). But now that I see this in the intervention, these sentences seem a bit weird when someone decides to immediately continue with the goal-setting dialog after the previous one (as the coach says hi again and asks how the user is doing in the middle of a conversation). I think it would be better to leave those sentences out if possible?
![WhatsApp Image 2023-08-22 at 15 32 25](https://github.com/PerfectFit-project/testing-tickets/assets/91131769/5cece57c-a817-480f-81f4-829c0486511f)

**Comment by nelealbers** [comment]
> I was testing the intervention with the smartwatch connection.
> 
> 1. After I finished the future-self video dialog (during preparation phase), it immediately started the goal-setting dialog, without a scheduling dialog in between (see screenshot). However, I believe that the scheduling dialog first needs to be shown right?

@Milonvv  There is currently no rescheduling dialog implemented before the goal-setting dialog. I remember that the rescheduling in the preparation phase was originally after one component had been finished to see if the user would want to do another component. Maybe when that was removed, we never added the rescheduling to the start instead. Since nothing is going wrong here, I would create a low-priority issue here.

> 2. This is a smaller issue, but the goal-setting dialog starts now with 'Hoi, wat leuk om je weer te spreken' (Hi, so nice to speak to you again) and then 'Hoe gaat het met je?' (How are you?). But now that I see this in the intervention, these sentences seem a bit weird when someone decides to immediately continue with the goal-setting dialog after the previous one (as the coach says hi again and asks how the user is doing in the middle of a conversation). I think it would be better to leave those sentences out if possible?

I will also create a low-priority issue for this.

**Comment by Milonvv** [comment]
@nelealbers @aversluis1 

Thanks @nelealbers!

Regarding issue 1: I do think that it is quite important that the user gets the rescheduling dialog before the goal-setting dialog since the goal-setting dialog is very long. If not, the chance is probably higher that they do not finish the goal-setting dialog in one go. Or is that not a big problem?

**Comment by nelealbers** [comment]
> @nelealbers @aversluis1
> 
> Thanks @nelealbers!
> 
> Regarding issue 1: I do think that it is quite important that the user gets the rescheduling dialog before the goal-setting dialog since the goal-setting dialog is very long. If not, the chance is probably higher that they do not finish the goal-setting dialog in one go. Or is that not a big problem?

@Milonvv The issue is that adding the rescheduling dialog requires changing logic, which might introduce new problems. So at this point, we want to change logic only when this is crucially needed because something is currently not working. The goal-setting dialog also happens to be one that people do not have to restart from the very start if they stop replying somewhere in the middle. We implemented this for the goal-setting dialog and the weekly reflection dialog I believe.

**Comment by Milonvv** [comment]
@nelealbers Ah yes, I understand (: Low priority then indeed

**Comment by Milonvv** [comment]
@nelealbers @wbaccinelli Btw I noticed that there is also no scheduler after the goal-setting, just before the first aid kit video (explanation). I just thought I let you know, in case you do decide to look at the schedulers
